stages:
  - build
  - deploy
  
before_script:
  - export GRADLE_USER_HOME=/Users/julien/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches 

build:
  stage: build
  tags: dxrest
  script:
    - ./gradlew jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master