stages:
  - build
  - deploy
  
before_script:
  - export GRADLE_USER_HOME=/Users/julien/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches 

build:
  stage: build
  script:
    - ./gradlew jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
    
deploy:
    stage: deploy
    script:
      - docker cp build/libs/dxrest-1.0.jar c491ab7ff20e:/home/root/dxram/dxapp