image: java:8

stages:
  - build
  - test
  - deploy

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches 

build:
  stage: build
  script:
    - ./gradlew jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
    
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r swagger/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master

test:
  stage: test
  script:
    -  ./gradlew testClasses
    