stages:
  - build
  - deploy
  
before_script:
  - export GRADLE_USER_HOME=/Users/julien/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches 

build:
  stage: build
  script:
    - ./gradlew jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
    
deploy:
    stage: deploy
    script:
      - docker cp build/libs/dxrest-1.0.jar dxrest:/home/root/dxram/dxapp
      - docker run -p 8009:8009 -it --entrypoint /bin/bash dxrest -p 'run.sh'